version: "3.9"

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    container_name: db_khanto 
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_khanto
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      DEBUG: 'true'
      DJANGO_SECRET_KEY: mysecretkey
      DATABASE_URL: postgres://myuser:mypassword@db:5432/postgres
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    container_name: backend_khanto
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db-data:
  pgadmin_data: